# Generated by Django 4.2.23 on 2025-07-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TitanicPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('fare', models.FloatField(blank=True, null=True)),
                ('survived', models.BooleanField(choices=[(0, 'Não Sobreviveu'), (1, 'Sobreviveu')])),
                ('embarked', models.CharField(blank=True, choices=[('C', 'Cherbourg'), ('Q', 'Queenstown'), ('S', 'Southampton')], max_length=1, null=True)),
                ('pclass', models.IntegerField(blank=True, choices=[(1, 'Primeira Classe'), (2, 'Segunda Classe'), (3, 'Terceira Classe')], null=True)),
            ],
        ),
    ]
